---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui-ingress
spec:
  rules:
  - host: app.geckzone.ru
    http:
      paths:
      - path: "/"
        backend:
          serviceName: ui
          servicePort: 8000
